### ISSUE TITLE
Проверка на NaN

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_13#1]
https://github.com/xydoy92/lesson_13/blob/28688af1f39c31831adb0518f11b96b09b9b74a6/script.js#L25

По поводу проверки на NaN, обрати внимание сюда - https://www.w3schools.com/JSREF/jsref_isnan_number.asp#:~:text=isNaN()%20method%20determines%20whether,Otherwise%20it%20returns%20false.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/isNaN

**Comment by xydoy92** [comment]
Done!
